google/bumble

bumble/device.py

These are critical pairing modes. SC(Secure Connection) and SSP(Secure Simple Pairing) determine the procedure and algorithem in authentication.
Besides, LE_Host_Support perameter is disabled in controllers by default(Vol. 4, Part E, 7.3.39), so a write command is necessary to make sure LE is enabled or not.

Make pairing and link mode configurable

---

bumble/gatt.py
bumble/profiles/heart_rate_service.py
examples/battery_server.py
examples/heart_rate_client.py
examples/heart_rate_server.py

Simple implementation of the standard HR profile, with client and server example apps.
Tested with virtual and physical HR sensors.

add support for the heart rate service

---

apps/console.py

I noticed that the 'write' command in `console.py` is unimplemented.
Here's an attempt at adding a `do_write()` handler.
Syntax is `write <attribute> <value>`. Supports a value of type string,
hexadecimal string, or integer.
Ex:
- `write 180D.2A38 hello`
- `write 180D.2A38 0xbeef`
- `write 180D.2A38 123`
Write with response method is used if supported by characteristic,
otherwise write without response.
Tested with run_gatt_server.py example to verify sent data.

Implement 'write' command for console.py

---

README.md

Added some improvements to the top-level README to help with new developer onboarding.

[docs] Add some getting started information to the top-level README.

---

setup.cfg

add long description

---

bumble/gatt.py
bumble/gatt_server.py
bumble/hci.py
tests/self_test.py

Add a test to check that we can read characteristics of all sizes, regardless of MTU size.
Also includes a small fix for characteristic adapters

add long read self test

---

bumble/l2cap.py
bumble/rfcomm.py

EventEmitter was being re-imported by mistake in two places rather than imported directly

fix imports

---

.github/workflows/python-build-test.yml
setup.cfg
tasks.py

Added two tasks to tasks.py, release and release_tests.
Applied black formatter

Added release tasks

---

bumble/gatt_client.py
bumble/gatt_server.py
tests/gatt_test.py

The ATT MTU must be the same for the GATT client and server on the same device for a given connection.
With this PR, the ATT MTU is only maintained in one place (the connection) instead of locally and separately on the client and server.
Added a quick test.

maintain the att mtu only at the connection level

---

setup.cfg

add controller-info CLI app to setup

---

bumble/controller.py

In one of the refactors the command address_resolution field was changed to address_reslution_enable but the controller code was not updated.

Fix address resolution handling

---

apps/console.py

New commands:
* scan on filter=address:pattern
* filter address <filter pattern>

Add runtime switch for filtering by address.

---

bumble/core.py
bumble/device.py

Fixes #49 
We may need to add some tests ?

device: raise a `CommandTimeoutError` error on command timeout

---

apps/console.py
bumble/core.py
bumble/device.py
bumble/hci.py
bumble/host.py
tests/core_test.py
tests/device_test.py

Device improvements

---

bumble/gatt.py
bumble/gatt_server.py
tests/gatt_test.py

* Converted CharacteristicDeclaration implementation to class
* Added ability to get a gatt_server attribute by service UUID, characteristics UUID, descriptor UUID

Added class CharacteristicDeclaration, gatt_server getters

---

.github/workflows/python-build-test.yml

Followed instructions here: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#using-the-python-starter-workflow

Test all python versions in CI

---

bumble/controller.py
bumble/device.py

This should fix the issue reported in #106.

support more commands in controller.py

---

apps/console.py
bumble/controller.py
bumble/transport/pyusb.py
bumble/transport/usb.py

`show attributes` wasn't being populated since `show_attributes()` was never called.
Also updated `show attributes` to match the color and indentation of `show services`

Fix `show attributes`

---

bumble/host.py

host: fixed `.latency` attribute error

---

bumble/core.py
bumble/device.py
bumble/gatt.py
bumble/gatt_server.py
bumble/hci.py
bumble/host.py
bumble/keys.py
bumble/sdp.py
bumble/smp.py
bumble/transport/__init__.py
bumble/transport/common.py
bumble/utils.py
tests/core_test.py

It's **very** not complete, just a small subset

overall: add types hints to the small subset used by avatar

---

bumble/device.py

Ran via:
```
pytype --pythonpath . ./bumble/device.py
```

Used pytype to find some missing types / fix small issue

---

bumble/device.py
bumble/hci.py
bumble/host.py
tests/hci_test.py

- bug fix:  [Fix a bug in HCI_Object.dict_from_bytes](https://github.com/google/bumble/commit/d55d53201ae65726ac0a76e7cda9d041bdd3e310)
- features
-  [Allow Device.enable_classic to be configurable](https://github.com/google/bumble/commit/5b7966da54b93298b11e3945a6b16834399fec63)
- [Add implemenetation of HCI_PIN_Code_Request_Reply_Command](https://github.com/google/bumble/commit/0e680e5cd465702f7abcd153b5bbab0066ee24f2)
- [Add on_pin_code_request to support legacy BT classic pairing](https://github.com/google/bumble/commit/1036accba1fc857bba7c63efe53ebf5879b5e9b0)

Add 1 bug fix and a few features in bumble

---

bumble/controller.py
bumble/link.py
tests/a2dp_test.py
tests/self_test.py

I want to test some features which can only work on Classic Bluetooth, such as role switching(in the following commits). However, we cannot rely on RootCanal because it's not mature as well.
The first commit centralize Local Linked Devices usage to a shared util module so that the following change won't change a lot. Then, I rename the original `LocalLink` class to `LocalLeLink`, and add a `LocalClassicLink` class to handle classic transport.
For the Remote Link path, I am not sure what we should do for it.

Add Classic Bluetooth link support

---

apps/console.py
bumble/att.py
bumble/gatt_client.py

Added via code inspection (not via a tool like pytype)

Add some missing types to apps/console.py, bumble/gatt_client.py

---

bumble/device.py
bumble/hci.py
bumble/smp.py
tests/hci_test.py

* fix HCI_PIN_Code_Reply_Command  implementation
* fix on Device.on_pin_code_request

Fix HCI_PIN_Code_Reply_Command 

---

apps/console.py
bumble/att.py
bumble/gatt.py
bumble/gatt_client.py
tests/gatt_test.py

Add a command to update the local gatt server, and notify/indicate subscribes (if any)

Add `local-write` to bumble-console

---

bumble/smp.py

Though in the spec this is not allowed, but in some ambiguous cases such as SMP over BR/EDR or we want to test how remote devices handle invalid pairing requests, we still need to allow this behavior, with some logs to let users know it's invalid.

SMP: Determine initiator by direction instead of role

---

bumble/core.py
bumble/device.py
bumble/gatt.py
bumble/keys.py
bumble/pairing.py
bumble/smp.py
tests/core_test.py

Overall fixes and improvements 

---

apps/pandora_server.py
bumble/pandora/__init__.py
bumble/pandora/config.py
bumble/pandora/device.py
bumble/pandora/host.py
bumble/pandora/security.py
bumble/pandora/utils.py
pyproject.toml
setup.cfg

See [asop/2584359](https://android-review.git.corp.google.com/c/platform/external/python/bumble/+/2584359) for details.

pandora: import bumble pandora server from avatar

---

bumble/gatt.py

gatt: reset args ordering to original

---

apps/pair.py
apps/scan.py
apps/unbond.py
bumble/device.py
bumble/keys.py
bumble/smp.py
tests/keystore_test.py

Add identity address to pairing event.
Improve the doc/interface/implementation of the Json. KeyStore.

pairing event improvement

---

bumble/pandora/host.py
bumble/pandora/security.py

break the import lines so it's easier to use copybara to replace the imports.

reformat protobuf import

---

bumble/core.py
bumble/l2cap.py

Also slightly refactor L2CAP channel tables. The original implementation mix BR/EDR and LE channels.

Add type hints to L2CAP module

---

bumble/device.py
bumble/smp.py
tests/self_test.py

* Auto add device to resolving list after pairing
* Add a flag to determine whether address resolution offlaod is enabled

Support address resolution offload

---

bumble/sdp.py
tests/__init__.py
tests/l2cap_test.py
tests/sdp_test.py
tests/test_utils.py

`DataElement` is left untyping, because its value type is not easy to handle.

Typing SDP and add tests

---

bumble/drivers/__init__.py

platformdirs is not available in Android

Make platformdirs import lazy

---

apps/show.py
bumble/drivers/rtk.py
bumble/hci.py
bumble/vendor/android/hci.py

This structure makes it easier to define vendor-specific commands and events.
Also included are some of the Android vendor-specific commands and events (incomplete).

add support for vendor HCI commands and events

---

setup.cfg
web/bumble.js

Address issue described in #284

make cryptography a valid dependency for emscripten targets

---

setup.cfg
web/bumble.js

Revert "make cryptography a valid dependency for emscripten targets"

---

apps/pandora_server.py

Pandora server has it's own config that we load from the 'server' property of the current bumble config file

pandora_server: Load server config

---

bumble/utils.py
tests/utils_test.py

From https://github.com/google/bumble/pull/292#issuecomment-1727009102

Add Pyee EventWatcher

---

bumble/l2cap.py

Using `self.State` because the class name may change in the future.

L2CAP: Refactor states to enums

---

bumble/transport/android_emulator.py
bumble/transport/android_netsim.py
bumble/transport/common.py
bumble/transport/ws_client.py

Netsim supports the notion of an instance number. This allows the Bumble netsim transport syntax to specify it.

support netsim instance numbers

---

rust/src/cli/l2cap/client_bridge.rs
rust/src/cli/l2cap/mod.rs
rust/src/cli/l2cap/server_bridge.rs

* Context vars can be injected directly into Rust future and spawned with tokio

Remove unncecesary steps for injecting Python event loop

---

bumble/avdtp.py
tests/avdtp_test.py

Still, many commands wrappers are left untyped. Maybe in another PR we can replace `send_command()` with an overloaded form, which mapping command to their responses.

Typing AVDTP

---

bumble/pandora/security.py

Listeners are not wrapped by try-catch, so when there are some errors, listeners will keep running and stuck the thread.

Pandora: Handle exception in WaitSecurity()

---

apps/bench.py
apps/gg_bridge.py
apps/l2cap_bridge.py
apps/speaker/speaker.py
bumble/l2cap.py
bumble/profiles/asha_service.py
bumble/rfcomm.py
bumble/sdp.py
examples/run_a2dp_sink.py
examples/run_a2dp_source.py
examples/run_asha_sink.py
tests/a2dp_test.py
tests/l2cap_test.py
web/speaker/speaker.py

Rust part is remained because I am not very familiar with them.

Cleanup legacy L2CAP API usage

---

bumble/device.py
bumble/gatt_client.py

I am trying to use these APIs to conduct CSIP tests, but I found they don't have correct annotations.

Typing GATT Client and Device Peer

---

bumble/gatt_client.py
tests/gatt_test.py

See https://github.com/google/bumble/issues/354

fix #354 (gatt unsubscribe)

---

apps/pair.py

No matter pairing fails or not, make linger effective

Improve the linger option of bumble-pair

---

bumble/hid.py
examples/run_hid_device.py

сhanged concatenation of strings to f-strings to improve readability and unify with the rest of code

сhanged concatenation of strings to f-strings to improve readability

---

apps/bench.py
apps/controller_info.py

Helps measuring the HCI transport latency to a controller.

add support for HCI latency probing

---

apps/scan.py

This is convenient when scanning and resolving addresses for devices of which you have the IRK but are not paired with.

allow passing IRKs as arguments to scan.py

---

extras/android/BtBench/app/src/main/AndroidManifest.xml

Enable the application to use SDK >= 34

Update the Bumble BT Bench AndroidManifest.xml

---

setup.cfg

Update to the latest version of RootCanal.

update to rootcanal 1.4

---

bumble/hfp.py
examples/run_hfp_handsfree.py

* Store active codec in protocol object.
* Emit unsolicited AG responses as events.
* Implement enhanced call status (CLCC).
* Also rewrite docstrings.

HFP: State memory and event emission

---

bumble/pandora/host.py

change advertising type from high duty to low duty
Test: python le_host_test.py -c config.yml --test_bed android.bumbles --tests "test_scan('connectable','non_scannable','directed',0)" -v

pandora host: change AdvertisingType

---

rust/CHANGELOG.md
rust/Cargo.lock
rust/Cargo.toml
rust/README.md
rust/src/wrapper/controller.rs
rust/src/wrapper/hci.rs
rust/src/wrapper/l2cap.rs

The crate is already published from this commit. Please tag as `rust-v0.2.0`.

Bumble crate 0.2.0

---

bumble/hfp.py
examples/hfp_handsfree.html
examples/run_hfp_handsfree.py

Rework HFP example

---

bumble/hfp.py
tests/hfp_test.py

* Support all Call Hold Operation
* Support CLI Presentation
* Support Voice Recognition
* Support RING and Volume Changes
* [AG] Support Enhanced Call Status
* Minor fixes

Add more HFP command suppport

---

bumble/hfp.py
tests/hfp_test.py

* Fix misplaced arguments
* Fix tests

Fix HFP query call status

---

web/bumble.js

This PR introduces an asynchronous queue to the `PacketSink` class, ensuring that the write operation is properly awaited.

bumble.js(PacketSink): Implement asynchronous packet processing

---

bumble/device.py

Advertising auto-restart was broken a while back. Upon disconnection, `self.legacy_advertiser` was set to `None` too early, so the `once` event handler was never set.

fix legacy advertising auto restart

---

apps/bench.py
apps/controller_info.py
bumble/hci.py
bumble/rfcomm.py
extras/android/BtBench/app/src/main/java/com/github/google/bumble/btbench/Model.kt

Allow requesting a specific role switch after connection in the Bench app.

bench role change

---

.devcontainer/devcontainer.json

devcontainer.json allows github's codespaces to be created with bumble's dependencies already installed

Add devcontainer.json

---

bumble/device.py

In comparison to standard scan, interlaced scan can significantly improve the speed to be paged or inquiried by remote. This feature is commonly used by modern Classic devices.

Support Interlaced Scan config

---

extras/android/BtBench/app/src/main/java/com/github/google/bumble/btbench/MainActivity.kt
extras/android/BtBench/app/src/main/java/com/github/google/bumble/btbench/Scan.kt

invoked via `adb shell am start -n com.github.google.bumble.btbench/.MainActivity --es autostart scan`

BtBench: Add Scan functionality

---

bumble/pandora/l2cap.py

* Craft the PandoraChannel from the connection_handle and the source_cid
* Fix race on waitDisconnection
* Add ChannelContext to enable mutliple channels on the service

Pandora: refactor l2cap service

---

bumble/profiles/aics.py
bumble/profiles/vcp.py
tests/aics_test.py
tests/vcp_test.py

aics: make it a secondary service

---

bumble/device.py

Fixes a typo that specifies the type of address

Fix typo in comment

---

bumble/controller.py
bumble/device.py
bumble/hci.py
tests/device_test.py

* Support Periodic Advertising
* Controller: Add basic advertising support
* Fix some test cases

Support Periodic Advertising

---

bumble/hfp.py
examples/run_hfp_gateway.py
tests/hfp_test.py

add super wide band constants

---

bumble/l2cap.py
bumble/sdp.py
tests/sdp_test.py

Fix for #601 
(also includes monitor cleanup of types and handling of request/response patterns)

SDP: enforce MTU limits

---

bumble/device.py
bumble/hci.py
bumble/host.py
bumble/smp.py
bumble/utils.py
examples/cs_initiator.json
examples/cs_reflector.json
examples/run_channel_sounding.py

Add basic HCI sequence support and examples. Ranging Profile / Service will be implemented in another PR.

Channel Sounding

---

apps/bench.py
bumble/device.py
examples/mobly/bench/one_device_bench_test.py
examples/mobly/bench/sample_config.yml
extras/android/BtBench/app/build.gradle.kts
extras/android/BtBench/app/src/main/AndroidManifest.xml
extras/android/BtBench/app/src/main/java/com/github/google/bumble/btbench/Advertiser.kt
extras/android/BtBench/app/src/main/java/com/github/google/bumble/btbench/AutomationSnippet.java
extras/android/BtBench/app/src/main/java/com/github/google/bumble/btbench/Connection.kt
extras/android/BtBench/app/src/main/java/com/github/google/bumble/btbench/Gatt.kt
extras/android/BtBench/app/src/main/java/com/github/google/bumble/btbench/GattClient.kt
extras/android/BtBench/app/src/main/java/com/github/google/bumble/btbench/GattServer.kt
extras/android/BtBench/app/src/main/java/com/github/google/bumble/btbench/L2capClient.kt
extras/android/BtBench/app/src/main/java/com/github/google/bumble/btbench/L2capServer.kt
extras/android/BtBench/app/src/main/java/com/github/google/bumble/btbench/MainActivity.kt
extras/android/BtBench/app/src/main/java/com/github/google/bumble/btbench/Model.kt
extras/android/BtBench/app/src/main/java/com/github/google/bumble/btbench/Packet.kt
extras/android/BtBench/app/src/main/java/com/github/google/bumble/btbench/Pinger.kt
extras/android/BtBench/app/src/main/java/com/github/google/bumble/btbench/Ponger.kt
extras/android/BtBench/app/src/main/java/com/github/google/bumble/btbench/Receiver.kt
extras/android/BtBench/app/src/main/java/com/github/google/bumble/btbench/Sender.kt
pyproject.toml

These were supported by the UI, but not yet by the mobly snippet API. See examples.

add startupDelay and connectionPriority params to BtBench snippets

---

docs/mkdocs/src/apps_and_tools/auracast.md

This file was missing from a recent auracast PR.

add auracast doc

---

apps/bench.py
bumble/device.py
bumble/hci.py
extras/android/BtBench/app/src/main/java/com/github/google/bumble/btbench/Advertiser.kt
extras/android/BtBench/app/src/main/java/com/github/google/bumble/btbench/MainActivity.kt
extras/android/BtBench/app/src/main/java/com/github/google/bumble/btbench/Model.kt

fix numeric entries and phy request

---

.github/ci-gradle.properties
.github/workflows/gradle-btbench.yml
extras/android/BtBench/.gitignore
extras/android/BtBench/app/src/main/AndroidManifest.xml
extras/android/BtBench/app/src/main/java/com/github/google/bumble/btbench/Advertiser.kt
extras/android/BtBench/app/src/main/java/com/github/google/bumble/btbench/GattServer.kt
extras/android/BtBench/app/src/main/java/com/github/google/bumble/btbench/L2capServer.kt

Temporarily fix some lint errors, but should be fix better in the future.

Add a workflow to build btbench

---

bumble/profiles/hap.py

HAS can be run in synchronized mode, requiring a server to be able to communicate with another CL.
This CL is doing a quick implementation of such functionality for preset selection.

Implement optional synchronization for has

---

bumble/avrcp.py

* Enforce type checking
* Fix typo

Fix AVRCP errors

---

bumble/hci.py
bumble/vendor/android/hci.py

* Make all enums in hci spectable
* Rename HCI_Extended_Event.dataclass_event to HCI_Extended_Event.event and remove the old one
* Minor changes in vendor/android/hci.py

Migrate all HCI_Extended_Event to dataclasses

---

rust/examples/scanner.rs
rust/src/adv.rs
rust/src/cli/l2cap/client_bridge.rs
rust/src/cli/l2cap/mod.rs
rust/src/cli/l2cap/server_bridge.rs
rust/src/cli/usb/mod.rs

Due to recent stable version change, some Rust CI cannot pass.
https://github.com/google/bumble/actions/runs/16016093865/job/45182918555

Fix Rust linter errors

---

bumble/drivers/intel.py
bumble/drivers/rtk.py
bumble/hci.py
bumble/vendor/android/hci.py
bumble/vendor/zephyr/hci.py
tests/hci_test.py

* Add SpecableFlag to handle flag fields
* Migrate all HCI_Command to dataclasses
* Fix some typos

Migrate all HCI_Command to dataclasses

---

bumble/l2cap.py
tests/l2cap_test.py

- Correct length calculation
- Rename data -> payload to avoid name collision with fields
- Remove __init__
- Add some tests

Fix L2CAP_Control_Frame errors

---

bumble/profiles/ams.py
examples/run_ams_client.py

Simple AMS service implementation. Only the client is functional. A stub of the server class is present, but not functional.
An example app allows testing with an iPhone: observer player/queue/track changes, and control commands can be sent over a TCP connection.

basic AMS implementation

---

.github/workflows/code-check.yml
.github/workflows/codeql-analysis.yml
.github/workflows/gradle-btbench.yml
.github/workflows/python-avatar.yml
.github/workflows/python-build-test.yml

This should allow running workflows manually from the GH Web UI.

enable manual workflow runs

---

bumble/device.py

Since the PR for typing is getting messy after modification of connectionParameters changes, create a new simple PR for device. (No behavior change in the commit.)

Add typing for device.py
