bumble/device.py
bumble/host.py

Disconnection events were emitted from the Device object instead of the Connection object. This PR fixes that.

fix the routing of disconnection events

---

bumble/transport/usb.py

Previously, the close method would hang waiting on the future to be
done.

Use threadsafe call when setting event_loop_done

---

bumble/device.py
bumble/hci.py
examples/battery_client.py
examples/heart_rate_client.py

* Device.connected_to connects to a peer as a context manager.
* The peer is disconnected when leaving the context
* Will perform discovery automatically on connecting, if requested
* Added HCI_StatusError that can be raised when a HCI Command Status
event is received that doesn't show "PENDING" as status
* Added Connection.sustain to wait for a timeout or disconnect
* Peer.sustain also maps to Connectin.sustain
* Updated battery_client.py to use .connected_to and .sustain

Adding in Device.connected_to context manager and Peer.sustain

---

apps/console.py
bumble/device.py
bumble/gatt_client.py
tests/gatt_test.py

Subscribe command will enable notify or indicate events from the
characteristic, depending on supported characteristic properties, and
print recevied values to the output window.
Unsubscribe will stop notify or indicate events.
Rename find_attribute() to find_characteristic() and return a
characteristic for a set of UUIDS, a characteristic for an attribute
handle, or None.
Print read and received values has a hex string.
Add an unsubscribe implementation to gatt_client.py. Reset the CCCD bits
to 0x0000 and remove all subscribers for a characteristic, since no more
notify or indicates events will be comming.

Add subscribe and unsubscribe commands to console.py

---

bumble/device.py

For remote-initiated test cases, we need Bumble to be scan-configurable.

Delegate Classic connectable and discoverable

---

README.md
apps/usb_probe.py
bumble/device.py
bumble/host.py
bumble/transport/usb.py
docs/mkdocs/src/apps_and_tools/usb_probe.md
docs/mkdocs/src/transports/usb.md
setup.cfg

This PR adds a simple tool to list USB devices and print the strings that may be used as a Bumble transport name to refer to them.
It also improves compatibility with older devices that may not be 100% compliant with the spec w/r/t how event masks are set.
Finally, this fixes a bug when interacting with controllers that report (0,0) for LE-specific ACL buffer size and counts.
NOTE: some USB dongles are very flaky, and can easily get into a non-working or stale state. There doesn't yet seem to be an easy way to catch this situation and reset it automatically using the Python USB API. When that happens, re-opening the device a second or third time seems to work. This needs to be investigated further.

add usb_probe tool and improve compatibility

---

bumble/transport/usb.py

Some USB devices, like the Zephyr USB HCI app, don't use the "standard" endpoint addresses (0x81, 0x82 and 0x02) for their HCI interface (even though the Zephyr code seems to have the right value of 0x02 for the ACL_OUT endpoint address, somehow it comes out as 0x01 when the descriptors are obtained by a host, not sure why. See https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/usb/device/class/bluetooth.c#L35)
With this change, the endpoint addresses are looked up dynamically, so even a non-standard endpoint address will work.

add support for dynamic discovery of USB endpoint addresses

---

apps/usb_probe.py
bumble/transport/usb.py
docs/mkdocs/mkdocs.yml
docs/mkdocs/src/apps_and_tools/usb_probe.md
docs/mkdocs/src/transports/usb.md

Some USB devices don't use compliant descriptors for their interfaces. This PR allows forcing the auto-detection logic to use those devices nonetheless.
Also included is better way to detect compliant devices (devices where the BT class is set on the interfaces but not on the whole device), so they can be used as `usb:<index>` rather than requiring an explicit `usb:<vendor>:<product>`.
Finally, a `--verbose` option is added to `usb_probe.py` that will list all the endpoints for each enumerated device.

improve USB device detection logic

---

apps/show.py
apps/usb_probe.py

When installing a script with setup.cfg, the script needs to have a `main` function with no arguments (at least on Windows).

use arg-less main() functions in all scripts

---

bumble/gatt.py
bumble/gatt_client.py
tests/gatt_test.py

When calling `write_value(..., with_response=True)` on a proxy with a type adapter, the `with_response` parameter has to be supported.

support with_response on adapters

---

apps/console.py

Add command to clear scan results and known addresses. Useful for determining if a peripheral has stopped advertising.
Also, check if a scan is in progress before connecting. If it is, stop scanning. Some BT controllers will fail to connect while scanning.
Testing:
Can clear scan results before, during, and after scan. Can clear scan results while disconnected and connected.

add 'scan clear' command to console.py

---

bumble/gatt.py
bumble/hci.py
examples/keyboard.py

Some constants had typos and were renamed in a previous commit, but not all examples that used those constants renamed their imports.

use the correct constants as previously renamed

---

bumble/core.py
bumble/device.py
bumble/host.py
bumble/rfcomm.py
examples/run_classic_connect.py
tests/device_test.py

According to the specification nothing prevent the Host from creating multiple connections at the same time. This commit add this mechanisme by matching the `connection` and `connection_failure` events against the peer address.

classic: update `Device.connect` to allow parallels connection creation

---

apps/console.py

If a device configuration is not provided on startup, generate a random BT address instead of using a default static value of "F0:F1:F2:F3:F4:F5". This is helpful to avoid colisions when there are two instances of console.py running nearby.
Testing:
Started console.py and began advertising a few times. Scanned from a second instance of console.py and observed that the advertising address changed with each restart.

Use random address in console.py if device config is not provided

---

apps/console.py

Show configuration data about the Bumble device. Make this the default tab on startup.

Add a show device tab

---

apps/console.py

This was broken in a previous commit.
Use a short formatter so that it fits on the screen (don't print the filenames)

use a formatter object, not a string

---

bumble/device.py
bumble/hci.py

A previous commit broke `await device.connect()` for Classic connections when an address was passed that wasn't correctly set to PUBLIC. Since BR/EDR addresses can't be random or private, this PR forces the address type used in the comparison when filtering for connections in the event handler.

fix classic connection event filtering

---

bumble/device.py
bumble/gatt_client.py
tests/gatt_test.py

If characteristic supports Notify and Indicate, the prefer_notify option will subscribe with Notify if True or Indicate if False.
If characteristic only supports one property, Notify or Indicate, that mode will be selected, regardless of the prefer_notify setting.
Tested with a characteristic that supports both Notify and Indicate and verified that prefer_notify sets the desired mode.

Add prefer_notify option to gatt_client subscribe()

---

bumble/hci.py
tests/hci_test.py

This affect the way security keys are stored. For instance the same key can be used both as public and random, and it need to be stored separately one from each other.

address: add public information to the stringified value

---

tests/l2cap_test.py

The test was using unnecessarily many combinations, causing the test to take sometimes more than a minute. 
This more limited set should be enough.
(also, fix the assert syntax, parentheses are not needed)

lower the number of test cases for l2cap in order to speed up the test

---

bumble/rfcomm.py

Minor fixup. Change the order of arguments to ConnectionError to set the transport and address correctly in rfcomm.py on_dm_frame().

Swap arguments to ConnectionError in RFCOMM Multiplexer

---

apps/console.py
bumble/l2cap.py

Pyee's add_listener() method was not added until release 9.0.0. Bumble's setup.cfg specifies a minimum pyee version of 8.2.2.
Remove the call to add_listener() in l2cap.py. If the add_listener() API is prefered over the on(), another solution would be to bump the pyee version requirement.

Fix for 'Host' object has no attribute 'add_listener'

---

bumble/host.py

An earlier merge made a bit of a mess with the logic sequence in the host reset method. 
This went unnoticed, until I ran the code with a controller where `HCI_LE_READ_BUFFER_SIZE_COMMAND` was not supported...

fix sequencing logic broken by earlier merge

---

.github/workflows/python-build-test.yml
bumble/smp.py
setup.cfg
tasks.py
tests/import_test.py

a. `DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead` Updated call in `bumble/smp.py`
b. `ModuleNotFoundError: No module named 'bumble.apps'` Updated imports in `tests/import_test.py`
c. Added `pytest-html` for easier viewing of test results Added package in `setup.cfg`, and hook in `tasks.py`
d. Updated workflows to use `invoke test`
This is a partial fix of #81

Fix test failures

---

bumble/transport/usb.py

The `usb` transport was unconditionally detaching the kernel driver for an interface when claiming it (when supported), but wasn't re-attaching it when releasing the interface. As a result, a USB controller would stop being visible to the kernel after using this transport on Linux.
This PR uses `libusb`'s auto-detach feature, which will automatically detach, the re-attach, the kernel driver when the interface is claimed then released.

use libusb auto-detach feature

---

.gitignore
bumble/core.py
bumble/device.py
bumble/gatt.py
bumble/gatt_server.py
tasks.py
tests/core_test.py
tests/gatt_test.py

This PR adds support for bumble-console to be preloaded with gatt services via `--device-config`.
This PR also adds some type annotations.
Formally #66

Add `bumble-console --device-config` support for gatt services

---

bumble/device.py
tests/device_test.py

This will allow a test to:
a: add services to a device
b: reset services via `Server()`
c: add the default services back

Add Device::add_default_services()

---

apps/usb_probe.py
bumble/transport/pyusb.py
bumble/transport/usb.py
docs/mkdocs/src/transports/usb.md
setup.cfg

It would be nice to pip install bumble without having to first install the libusb system dependency. Expecially on platforms like Windows and Mac, without a default package manager.
The libusb_package Python package distributes prebuilt libusb-1.0 shared libraries for each OS and architecture as binary wheels for the pyusb project. Add this package as a dependency for bumble.
For the pyusb transport, the libusb_package.find() function is a drop-in replacement for pyusb.usb.core.find(). It searches the libusb_package site-packages path before system paths and creates a pyusb backend.
For the usb transport, use libusb_package.get_library_path() to return a path to the libusb-1.0 library in site-packages. If this path exists, create a ctypes DLL and init the usb1 backend. This only needs to …

Load libusb-1.0 shared library from libusb_package wheel

---

bumble/transport/hci_socket.py

Calling 
`python3 examples/device_information_server.py examples/device1.json hci-socket`
produces error:
`  File "/home/server/bumble/venv/lib/python3.10/site-packages/bumble/transport/hci_socket.py", line 100, in __init__
socket.fileno(), self.recv_until_would_block
AttributeError: module 'socket' has no attribute 'fileno'`
File `transport/hci_socket.py` was changed to fix this bug.

Fix bug when use hci-socket transport

---

bumble/device.py
bumble/hci.py

Some controllers don't like it when invoking HCI_LE_Set_Random_Address_Command with an all-0s address.
So, when using a device with a config where no random address is set, don't send such an address.

don't set a random address when it is 00:00:00:00:00:00

---

setup.cfg

The previous version was missing `tomli` as a dependency, thus breaking on some platforms.

fix libusb-package dependency

---

setup.cfg

I was wondering why black was re-formatting files differently form `main`.
I suggest this change to make sure it does not happen

build: fix version of packages running checks in CI

---

bumble/a2dp.py
pyproject.toml
setup.cfg

`bitstruct` has a C component and isn't distributed as pre-compiled for all platforms. `construct` seems like a good replacement (performance doesn't matter here).
Also, this should fix a field error with `AacMediaCodecInformation` (we were skipping 4 reserved bits somehow).

replace bitstruct with construct

---

bumble/utils.py

Nothing prevent the future to be completed before `on_event` call, this change fix that

utils: fix possible invalide state error while canceling future for `abort_on`

---

apps/pair.py
bumble/keys.py

As reported in #124 specifying a filename in a device config when using the `JsonKeyStore` keystore would fail.
Ex: `"keystore": "JsonKeyStore:mykeys.json"`

fix getting the filename from the keystore option.

---

.vscode/settings.json
apps/pair.py
bumble/smp.py
setup.cfg
tests/self_test.py

The timing when pairing with iOS/macOS with passkey wasn't correct (we would not send the peripheral public key soon enough).
Also included in this PR:
* remove dependency on aioconsole for the pair.py app
* fix the PairingDelegate base class to not use `_xxx` parameter names
* fix for pairing being stuck when pairing without secure connections

improve smp compatibility with other OS flows

---

bumble/hci.py
bumble/host.py
bumble/snoop.py
examples/run_device_with_snooper.py

Support for injectable snooper to capture the HCI packets between the host and the controller.
Included is a snooper implementation that supports the BTSnoop log record format, and an example app.

add snoop support

---

bumble/host.py
bumble/snoop.py
bumble/transport/__init__.py
bumble/transport/common.py
setup.cfg
tests/transport_test.py

When the BUMBLE_SNOOPER env variable is set, a Snooper instance will be automatically created when a transport is instantiated.
A file-based scheme is implemented, where a filename pattern is used to construct the path of the snoop log file.
ex:
export BUMBLE_SNOOPER=btsnoop:file:/tmp/bumble_{now:%Y-%m-%d-%H:%M:%S}_{pid}.log
--> when a transport is created, a BtSnooper instance will be instantiated, logging to the file: /tmp/bumble_2023-03-20-11:15:24_17011.log

add auto-snooping for transports

---

apps/bench.py
apps/controller_info.py
bumble/device.py
bumble/gatt_server.py
bumble/l2cap.py
bumble/rfcomm.py
bumble/utils.py
docs/mkdocs/mkdocs.yml
docs/mkdocs/src/apps_and_tools/bench.md
docs/mkdocs/src/apps_and_tools/index.md
docs/mkdocs/src/index.md
setup.cfg

This is a "swiss army knife" benchmarking tool that can be used to test the throughput and/or latency between two devices. 
Supported modes:
* GATT
* L2CAP CoC
* RFComm
Supported roles:
* Server (sends data as fast as possible)
* Receiver (receives data from a Server role and sends back a final ACK when the server is done sending)
* Ping (sends periodic PINGs)
* Ping (responds to PINGs)
* 
One device runs as the Central (with the ability to specify a custom Connection Interval and PHY), the other as the Peripheral.
The modes are independent of the roles and of the central/peripheral choice. So, for example, you can have a Central be a Sender as a GATT client (default), and the Peripheral be the Receiver as a GATT server. But you could also have the Central be a Receiver as a GATT client, …

add benchmark tool and doc

---

bumble/att.py
bumble/device.py
tests/gatt_test.py

before:
```
File "/home/alanrosenthal/code/fitbit/bumble/bumble/gatt.py", line 572, in __str__
f'Descriptor(handle=0x{self.handle:04X}, '
File "/home/alanrosenthal/code/fitbit/bumble/bumble/att.py", line 756, in read_value
self.permissions & self.READ_REQUIRES_ENCRYPTION
TypeError: unsupported operand type(s) for &: 'str' and 'int'
```

Fix small bug with services set via --device-config

---

bumble/att.py
bumble/device.py

* 'permission' instead of 'permissions'
* Also added a more user friendly error message when Attribute.string_to_permissions fails
```
TypeError: Attribute::permissions error:
Expected a string containing any of the keys, seperated by commas: READABLE,WRITEABLE,READ_REQUIRES_ENCRYPTION,WRITE_REQUIRES_ENCRYPTION,READ_REQUIRES_AUTHENTICATION,WRITE_REQUIRES_AUTHENTICATION,READ_REQUIRES_AUTHORIZATION,WRITE_REQUIRES_AUTHORIZATION
Got: 1
```
```
Exception: Error parsing Device Config's GATT Services. The key 'permission' must be renamed to 'permissions'
```

Fix typo when parsing device-config's gatt server

---

bumble/device.py
bumble/host.py

* Add role switch handler in host, device, device connection.
* There is a quirk that role change events may be received before HCI_Connection_Complete, especially on the responder side, or role switch is performed during connection establishment
Note: I didn't add any test because BR/EDR local test framework is not ready: https://github.com/google/bumble/pull/144

Support BR/EDR role switch & change events

---

bumble/smp.py

This function can return `None` to indicate a negative reply, update the type hint accordingly.

smp: fix `PairingDelegate.get_number` return type

---

apps/console.py
bumble/gatt_server.py
setup.cfg
tests/gatt_test.py

This PR adds a way to display the local gatt characteristics/descriptors values
If no connections, it shows the value of every characteristic/descriptor. When there's a connection, it shows the value for each specific connection - CCCDs are connection specific
This screen auto-updates every second

Add `show local-values`

---

bumble/gatt_client.py

` property` was really an int, and needed to be transformed into a `Characteristic.Properties`

Fix CharacteristicProxy __str__

---

apps/gg_bridge.py
bumble/device.py
bumble/keys.py

Instead of just using the device static random address, use the most likely identifier for the controller as the namespace for keystores:
* Try the public address first if the controller has one
* Second choice is the static random address assigned to the controller
* Otherwise: default namespace.

use device public or static address for keystore namespace

---

LICENSE

This PR integrate the licence of 'bumble/colors.py' into LICENCE file.

LICENCE: recorde colors.py licence

---

bumble/device.py

Some controllers, like Zephyr-based controllers, don't like it when passing multiple connection parameters in the connection request (even if the PHY is supported). For example, with a Zephyr controller (from the Zephyr HCI USB example), when not specifying explicit parameters in the connection request (which is what most of the tools and examples do), this would lead
to the controller returning `HCI_UNSUPPORTED_FEATURE_OR_PARAMETER_VALUE_ERROR`.
This change is for only specifying default values for 1M if no explicit preferences are passed (you can still pass arbitrary sets if you want, this only changes the default). It also seems reasonable to pick only 1M by default, since that's the expected baseline for all controllers.

only use 1M parameters by default

---

apps/pair.py
bumble/device.py
bumble/host.py
bumble/keys.py
bumble/rfcomm.py
bumble/smp.py
examples/hfp_handsfree.json
tests/self_test.py

Somehow the connection role wasn't handled quite right for Classic connections (because we don't know the role at the time of connection, the role is temporarily unknown). This caused CTKD to fail, because over a Classic connection, as a peripheral, the SMP would not distribute keys in response to an SMP pairing request since it incorrectly thought it was the central.
This PR removes the `role` attribute in the host-level connection object (it's actually not needed there).
Also, this removes the `resolved_peer_address` property for Classic connections, since there's no concept of resolvable keys there, that property isn't relevant.
Finally, there's limited support for disabling SMP over Classic connection, for when a device doesn't want to participate in Classic CTKD.

fix role state for classic connections

---

apps/pair.py
bumble/device.py
bumble/host.py
bumble/pairing.py
bumble/smp.py
tests/self_test.py

This moves the PairingDelegate to its own file. It is thus clearer that the PairingDelegate interface can serve for both Classic and LE pairing.
Also included is a fix for one of the Classic pairing modes, where, according to the spec, the behavior of the responder depends on the `io_capability` of the initiator, so that value is now stored in the Connection object.
Tested against Android and macOS (with all 4 Classic `io_capability` types, both as an initiator and responder, even though the Android and macOS sides are always `DisplayYesNo`)

refactor PairingDelegate

---

bumble/keys.py

use `os.replace` instead of `os.rename`.

fix keystore save implementation for windows

---

docs/mkdocs/src/transports/ws_client.md
docs/mkdocs/src/transports/ws_server.md

Those pages were wrongly just copy-pasted from other transports.

fix doc for ws-client ws-server transports

---

examples/run_scanner.py

The other data elements have a space, so I'm guessing that RSSI is intended to as well. Perhaps there's some subtle reason why it should have a space, though, in which case feel free to close this.
Output now looks like this:
```
>>> 58:D3:49:E7:40:DA/P [PUBLIC]:
RSSI: -67
[Flags]: LE General,BR/EDR C,BR/EDR H
[TX Power Level]: 4
[Manufacturer Specific Data]: company=Apple, Inc., data=0f08c00af4392b00040c10020f04
```

Add a space after RSSI

---

.github/workflows/python-build-test.yml
bumble/gatt.py
tests/gatt_test.py

Python 11's handling of enums has changed a bit, so the conversion to string behaves differently from before.
This should make the code and type checking compatible with the new modes.

compatibility with python 11

---

bumble/hci.py
tests/hci_test.py

This adds support for specifying field arrays in HCI packet definitions, in a way that's compatible with how this was done before with custom parsers (i.e for an HCI packet with an array of `some_field`, the object will have a `some_fields` property that is an array, including in the constructor.
To use this new syntax, use a array entry instead of a tuple for one of the `fields` definition in the class decorator (see `HCI_LE_Set_Extended_Advertising_Enable_Command` for an example.

add support for field arrays in hci packet definitions

---

bumble/pandora/device.py

pandora: add `tcp` option to transport configuration
* Add a fallback to `tcp` when `transport` is not set.
* Default the `tcp` transport to the default rootcanal HCI address.

pandora: add `tcp` option to transport configuration

---

bumble/controller.py
bumble/host.py
bumble/transport/common.py
bumble/transport/tcp_client.py

This allows calls to be unblocked from waiting for a response when the transport goes away.
The new sink method `on_transport_lost` is optional for sinks. A source should call it when it is terminated.

add sink method for lost transports

---

bumble/device.py
bumble/host.py
bumble/pandora/security.py

A refined version of https://github.com/google/bumble/pull/187
`on_ssp_complete()` is removed due to no usage, and this logic should be handled by applications.

Handle SSP Complete events

---

environment.yml
setup.cfg

The current grpcio version 1.51.1 fails to build on aarch64 based MacOS computers. Update the version of the grpcio and grpcio-tools packages to the latest 1.57.0 version. There are binary wheels available for this version from PyPi for aarch64 MacOS.
Also update the pip version for the Conda environment. It seems a newer version of pip is required to detect and install these wheels.
Testing:
invoke test passes and I can start the bumble-pandora-server successfully.
Fixes #259

Update grpcio and pip package versions

---

bumble/rfcomm.py
examples/run_rfcomm_server.py

Add support for RFComm service UUIDs to the RFComm server example

rfcomm with UUID

---

bumble/hfp.py
examples/run_hfp_gateway.py
tests/hfp_test.py

There are still many users using the original protocols. Though we are still in an early stage, deprecation should be slowly and responsible. Also, there is no alternative for AG and low-level usage.

Bring HfpProtocol back

---

apps/show.py
bumble/vendor/zephyr/hci.py
docs/mkdocs/mkdocs.yml
docs/mkdocs/src/platforms/index.md
docs/mkdocs/src/platforms/zephyr.md

Add HCI Zephyr vendor commands to read and write TX power
Create platforms/zephyr/hci.py with definitions of vendor HCI commands
to read and write TX power.
Add documentation for how to prepare an nRF52840 dongle with a Zephyr
HCI USB firmware application that includes dynamic TX power support and
how to send a write TX power vendor HCI command from Bumble

Add support for Zephyr HCI VSC set TX power command

---

bumble/transport/common.py

`wait_for_termination()` is not included because it's deprecated. Users can still access in a non-typed context.

Add terminated to TransportSource protocol

---

bumble/transport/hci_socket.py
setup.cfg

Not sure why this didn't show up before, but mypy started showing errors that were previously ignored (seems that mypy really needs ignore-error comments on each individual line.

mypy: ignore false positive errors

---

bumble/pandora/security.py
bumble/smp.py

Note: It's different from other delegation methods, but this mode looks more "Bumble"(considering the EE).
Alternative: If we still prefer PairingDelegate mode, we may add a `get_security_action(peer_address, auth_req)` method in PairingDelegate, which returns one of the following action, and perform the corresponding action:
* Ignore
* Pair
* Encrypt
* Refresh key

Handle SMP_Security_Request

---

.github/workflows/python-build-test.yml
rust/Cargo.lock
rust/Cargo.toml
rust/README.md
rust/pytests/assigned_numbers.rs
rust/src/adv.rs
rust/src/wrapper/logging.rs
rust/tools/file_header.rs

Added binary that can check for and add Apache 2.0 licenses. Run this binary during the build-rust workflow.

Add license header check for rust files

---

bumble/device.py

use correct own_address_type when restarting advertising

---

bumble/transport/ws_client.py

Somehow the implementation treated the parameters as for a TCP client, but for websockets, we need a full URL with a path (as per the documentation)

ws-client: make implementation match the doc

---

setup.cfg
web/bumble.js

Since only the special cryptography package bundled with pyodide can be used, relax the version requirement to anything that's version `39.*`.
Fix #284

Make cryptography a valid dependency for emscripten targets

---

bumble/device.py

This is a hot fix for a bug introduced by a recent PR.
I will self-approve this PR now because that bug breaks users right now. We can always adjust/revise if this fix isn't the right one.

don't delete advertising prefs on disconnection

---

bumble/hci.py
bumble/hfp.py
bumble/host.py
examples/run_hfp_gateway.py

I only added HCI packets and eSCO codec definitions, as well as host handler. For `device`, it's not easy to integrate SCO into current handlers.
I also tested the SCO HCI path on Android, with IBluetoothHci. Links can be created and controllers consistently report packets, but later packets are all 0. It's probably because the host didn't send any SCO packet?
Most USB dongles don't support eSCO, so I haven't tried to setup them legacy SCO.

eSCO codec/HCI definitions + Host support 

---

bumble/hid.py

* Remove unused imports
* Replace typing exceptions by better assertions

Cleanup HID module

---

apps/pair.py

Android performs additional service
discovery during pairing, otherwise
pairing fails.

Do not exit after pairing is finished

---

bumble/transport/usb.py

Move the event processing thread from the `UsbSource` class  to the `UsbTransport` class (it doesn't logically belong to just the source, since the sink also needs callbacks).
Remove unused `context` property in `UsbPacketSource`
Minor re-naming of some properties.

minor cleanup of the internals of the usb transport implementation

---

.vscode/settings.json
bumble/crypto.py
bumble/smp.py
tests/self_test.py
tests/smp_test.py

It seems sample input data provided in the spec is big-endian (just like other AES-CMAC-based functions), but all keys are in little-endian( HCI standard), so they need to be reverse before and after applying AES-CMAC.

Slightly refactor and fix CTKD

---

bumble/gatt.py

A few more UUIDS from the registered numbers list.
(Also, removed the ' Service' suffix for some UUIDS, to be consistent with the rest of the UUIDS naming conventions, which uses the exact strings from the SIG spec documents.
(eventually we'll generate the python files from the .yaml files now that they are published, the same way we do for the company IDs)

add a few uuids

---

bumble/transport/common.py

Many errors are raised in on_packet() callbacks, but currently it only provides a very brief error message.

Log track back in on_packet

---

bumble/controller.py
bumble/gatt_server.py
bumble/hci.py
bumble/profiles/bap.py
examples/leaudio.json
examples/run_unicast_server.py
tests/bap_test.py

Based on https://github.com/google/bumble/pull/356
Status: (Sink only) Play, pause, decoding are verified.

Audio Stream Control Service

---

bumble/drivers/__init__.py
bumble/drivers/common.py
bumble/drivers/rtk.py
bumble/host.py
bumble/transport/__init__.py
bumble/transport/android_emulator.py
bumble/transport/common.py
bumble/transport/hci_socket.py
docs/mkdocs/src/drivers/index.md
docs/mkdocs/src/drivers/realtek.md

This should allow a driver to interact with a controller, via the `host`, before any command, including RESET is issued.
See the example with the Realtek driver. 
Note that if a driver needs to send a command and receive a response before RESET is performed, it must set `host.ready = True` to allow the inbound packet processing to accept the packet even if no RESET has been done (by default, the host ignores packets from the controller that are received before a RESET).
Also included is a generic way to add HCI metadata to an HCI transport source. Previously, only certain transport sources would set metdata (USB would set `vendor_id` and `product_id`, which the Realtek driver uses to determine if it should try
to load a FW image). Now, a driver can be "forced" for a specific HCI source, …

support drivers that can't use reset directly.

---

bumble/crypto.py
bumble/gatt.py
bumble/profiles/cap.py
bumble/profiles/csip.py
examples/run_csis_servers.py
examples/run_unicast_server.py
tests/cap_test.py
tests/csip_test.py

Changes:
* RSI generation
* SIRK encryption
* Delegated SIRK reader
* Prand and random address generation
TODO:
* Encrypted SIRK. Requiring a change: https://github.com/google/bumble/pull/374#issuecomment-1857170345, so it would be implemented in another CL.
Test:
* csip_test, cap_test
* Manually pairing with Android CSIS client

Complete CSIP and CAP

---

extras/android/BtBench/app/src/main/java/com/github/google/bumble/btbench/L2capClient.kt
extras/android/BtBench/app/src/main/java/com/github/google/bumble/btbench/Model.kt

Somehow, Android doesn't negotiate a DLE change unless an MTU change is requested...

request MTU change after connection

---

apps/console.py
bumble/att.py
bumble/gatt.py
bumble/gatt_server.py
bumble/profiles/asha_service.py
bumble/profiles/bap.py
bumble/profiles/csip.py
bumble/utils.py
tests/bap_test.py
tests/gatt_test.py

This allows the `read` and/or `write` functions of `CharacteristicValue` to be async (or be sync functions that return an awaitable), without requiring them to be. The server will automatically adapt to both types.

support async read/write for characteristic values

---

apps/bench.py
apps/l2cap_bridge.py
bumble/l2cap.py
bumble/rfcomm.py
docs/mkdocs/src/apps_and_tools/bench.md
extras/android/BtBench/app/src/main/java/com/github/google/bumble/btbench/L2capClient.kt
extras/android/BtBench/app/src/main/java/com/github/google/bumble/btbench/Model.kt

Drain support helps pace senders that have a large amount of data ready to send at once.
Also included are a few more command line options for fine-tuning the test modes for the bench app.

l2cap & rfcomm drain support

---

apps/controller_loopback.py
bumble/hci.py

Add a command line utility to open a transport to a BT controller, put the controller into local loopback mode, and send and receive ACL data packets. Record the time it takes to send and receive all packets and calculate a throughput measurement in kB/s.
This utility is usefull for characterizing the speed of a transport to a BT controller (such as a TCP socket or serial port) without having to deal with a connected peer or the variability of over the air transmissions.
The transport CLI argument is required. The packet size and packet count arguments are optional. They default to the same values as the bumble-bench app.

apps: Add a controller loopback throughput test app

---

.vscode/settings.json
bumble/controller.py
bumble/device.py
bumble/hci.py
bumble/link.py
bumble/transport/__init__.py
tests/hfp_test.py
tests/test_utils.py

This provides a capability to test SCO virtually. We will also apply the same strategy to CIS.

Controller: SCO implementation

---

bumble/helpers.py
bumble/rfcomm.py
extras/android/RemoteHCI/app/build.gradle.kts
extras/android/RemoteHCI/app/src/main/java/com/github/google/bumble/remotehci/HciHal.java
extras/android/RemoteHCI/app/src/main/java/com/github/google/bumble/remotehci/HciServer.java

Even if the RFComm session has no sink (not very useful, but could happen in a test), we still need to update the credits.

update credits even without a sink

---

bumble/smp.py
tests/self_test.py

Since keystore.update() overwrites all existing keys, the existing link key will be wiped out. To avoid this, SMP also need to keep the key.

Save Link Key in CTKD over BR/EDR

---

bumble/device.py
bumble/smp.py
setup.cfg

Address generation offloading uses peer address as an entry of IRK, even in non-directed usage. By adding an empty entry containing local IRK to controller resolving list, controllers are able to generate RPA without pairing.

Support non-directed address generation offload

---

bumble/rfcomm.py
tests/rfcomm_test.py

* Correct PN window size (max/mask: 16 -> 7)
* Convert constants to enums
* Convert packet types to dataclasses
* Add basic connection test for RFCOMM

RFCOMM: Slightly refactor and correct constants

---

apps/controller_loopback.py

Bound the packet count CLI option. We're using the L2CAP header CID for a paket ID, so the max packet count value has to fit into this 16-bit field.
Add support for controllers that are LE only by checking the le_acl_packet_queue.max_size.
Tested with 65535 max packet count. Took 138 seconds at 481 kB/s with a USB BT dongle.

controller_loopback: LE support and max packet count

---

bumble/device.py
bumble/gatt_client.py
bumble/gatt_server.py
bumble/hci.py
bumble/host.py
bumble/l2cap.py
bumble/utils.py
examples/run_advertiser.py
examples/run_cig_setup.py
examples/run_csis_servers.py
examples/run_extended_advertiser.py
examples/run_extended_advertiser_2.py
examples/run_unicast_server.py
setup.cfg
tests/device_test.py
tests/gatt_test.py
tests/hci_test.py
tests/test_utils.py

This is an enhanced API for extended advertising which allows:
1/ using extended advertising commands for legacy advertising (keeping the original advertising API as-is)
2/ creating advertising set objects, which can be independently started/stopped/updated, using a new API.
The new/extended API also allows creating advertisements with legacy PDUs (very typical when you want to be compatible with older devices/phones) in addition to newer ones.
The unit tests aren't complete yet, because they will be easier to write once we merge the PR with basic support for extended advertising in the local controller class. Using Host mocks isn't a great way to test, because you need the full logic of a Controller to ensure that the sequence of events (for example, you need responses for some commands, …

extended advertising v2

---

apps/bench.py
bumble/rfcomm.py
bumble/sdp.py
tests/rfcomm_test.py
tests/sdp_test.py

* Add an RFCOMM (Client, Server) and SDP(Client only because Server is managed by device) context manager.
* Add an RFCOMM helper function to search channel from SDP.
* And some test cases.

Add RFCOMM and SDP context manager and search helper

---

apps/bench.py
bumble/avdtp.py
bumble/hid.py
bumble/l2cap.py
bumble/rfcomm.py
examples/run_a2dp_source.py
setup.cfg
tests/l2cap_test.py
tests/rfcomm_test.py

This adds options to the Bench app to control RFCOMM parameters.
Also included is a small fix for MTU negotiation in L2CAP (keeping track of both the local MTU and the peer MTU)

add rfcomm options and fix l2cap mtu negotiation

---

bumble/device.py

When legacy advertising set is disabled passively(by set termination), the legacy advertising set won't be released, and the next `stop_advertising()` call will try to disable it again and cause an error.

Fix double-disable legacy advertising set

---

.github/workflows/python-build-test.yml
rust/Cargo.toml

```
error: failed to compile `cargo-all-features v1.10.0`, intermediate artifacts can be found at `/tmp/cargo-installshCmAG`
Caused by:
package `clap v4.5.1` cannot be built because it requires rustc 1.74 or newer, while the currently active rustc version is 1.70.0
Try re-running cargo install with `--locked`
```

Bump Rust to 1.76.0

---

apps/show.py
bumble/helpers.py
bumble/transport/common.py

Show UTC timestamps when printing logs from a snoop log.

show timestamps from snoop logs

---

bumble/drivers/__init__.py
bumble/drivers/intel.py

This VSC enable host-initiated role-switching after connection.
Implement this VSC in a driver fashion.
Tests: `python avatar/cases/security_test.py -c avatar/cases/config.yml --test_bed usb.be200`
Test: avatar security_test with the Bluetooth Dongle Intel BE200

intel: send vsc INTEL_DDC_CONFIG_WRITE

---

bumble/drivers/intel.py
bumble/host.py
docs/mkdocs/src/drivers/index.md

An earlier merge of the driver broke the functionality for most users as it would always instantiate the driver even when not explicitly selected, and therefore send a vendor HCI command even to non-intel controllers.

fix intel driver probe

---

bumble/transport/pyusb.py
bumble/transport/usb.py
docs/mkdocs/src/transports/usb.md

Add a new moniker for usb and pyusb driver allowing to select the usb device using its bus id and port path like `usb:3-3.4.1`.

usb: Add usb path moniker

---

bumble/pandora/host.py

pandora_server: Parse FLAGS into advertising data

---

bumble/profiles/bap.py
examples/run_unicast_server.py
examples/run_vcp_renderer.py

The most important part is the Announcement Type. Advertising Targeted Announcement allows clients autoconnecting to servers.

Implement Unicast Server Advertising Data

---

apps/bench.py

On some versions of Python, the Event object created in the Central and Peripheral class initializers is called before the main asyncio loop is created, leading to an exception.
This moves the instantiation of the object into a local async function, which solves the problem.

delay creation of runner object

---

setup.cfg

Python 3.12 on an Apple Silicon mac had trouble installing grpcio. With this update, it works.

update some dependencies

---

.github/workflows/code-check.yml
.github/workflows/python-avatar.yml
setup.cfg

Address #471
This makes it easier to manage cross-package dependencies.
Users of pandora now will need to explicitly specify the `[pandora]` extra-require when installing.

update protobuf dep and make pandora install optional

---

setup.cfg

The upgrade to 4.x wasn't really needed, and breaks some users.

quick fix: revert to protobuf 3.12.4

---

bumble/hfp.py
examples/hfp_gateway.html
examples/hfp_gateway.json
examples/run_hfp_gateway.py

* Fix CLIP handler error
* Fix CMER handler error
* Implement AG +VGS +VGM +CCWA handler
* Fix wrong AG UUID (the original one is for HSP)
* Fix find_hf_sdp_record() may find AG record
* Implement an example UI for AG

HFP: Add AG example and fix errors

---

bumble/host.py

Support `check_status == True` when calling `send_command` for commands that return an `HCI_Command_Status_Event`. (not sure why this has not come up before...)

allow checking results for HCI_Command_Status_Event

---

bumble/rfcomm.py
tests/rfcomm_test.py
tests/test_utils.py

This race condition is not common since usually the initiator (no matter it's an L2CAP or RFCOMM channel) should send the first packet. However, in HFP, if it is AG opening the channel, AG cannot send the first packet, and HF may send AT+BRSF too quick that `open_dlc()` haven't returned yet.

RFCOMM: Handle packets received before DLC sink set

---

bumble/transport/common.py

Preserve transport metadata when wrapping with SnoopingTransport

Fix: Preserve transport metadata

---

apps/bench.py
apps/rfcomm_bridge.py
bumble/l2cap.py
bumble/rfcomm.py
bumble/sdp.py
extras/android/BtBench/app/src/main/java/com/github/google/bumble/btbench/SocketClient.kt
setup.cfg
tests/rfcomm_test.py

Simple app that offers a TCP<->RFCOMM bridge. A client mode and a server more are supported.
In client mode, the bridge waits for an inbound TCP connection, then initiates an outbound RFCOMM connection, then bridges the two bi-directionally.
In server mode, the bridge waits for an inbound RFCOMM connection, then initiates an outbound TCP connection, then bridges the two bi-directionally.

rfcomm bridge app

---

apps/auracast.py
bumble/core.py
bumble/device.py
bumble/hci.py
bumble/host.py
bumble/pandora/host.py
bumble/profiles/bap.py
bumble/profiles/le_audio.py
bumble/profiles/pbp.py
tests/core_test.py

This app is intended to support auracast features. To start with, only scanning for broadcasts is implemented. More functionality, including sending and receiving broadcasts, will be added in future PRs.

basic auracast app

---

bumble/device.py
bumble/host.py
tests/device_test.py

Some controllers (like the ASUS BT500) send the advertising set termination event *before* the connection complete event. At that time, the Connection object for connection_handle in the event isn't yet known. When that happens, we need to support remembering the address information until the connection complete event arrives.

support out of order advertising set termination / connection events

---

bumble/device.py
tests/gatt_test.py

`get_characteristics_by_uuid()` now allows a UUID to be passed to the service param. This allows for users to easily query for a service uuid and characteristic uuid with one API.

device.py: Update get_characteristics_by_uuid()

---

tasks.py
web/.gitignore
web/README.md
web/bumble.js

This command will build a wheel, copy it in the web directory, and create a file `packageFile` with the name of the wheel. If the correct override param is given, bumble.js will read `packageFile` and load that package.

Create `inv web.build`

---

bumble/avdtp.py

Delay report commands were not handled. This handles them by emitting an event with the delay value.

a2dp: emit delay_report

---

bumble/at.py
bumble/avc.py
bumble/avctp.py
bumble/avdtp.py
bumble/avrcp.py
bumble/codecs.py
bumble/colors.py
bumble/core.py
bumble/device.py
bumble/drivers/rtk.py
bumble/gatt_client.py
bumble/hci.py
bumble/l2cap.py
bumble/link.py
bumble/profiles/csip.py
bumble/profiles/heart_rate_service.py
bumble/rfcomm.py
bumble/sdp.py
bumble/smp.py
bumble/snoop.py
bumble/transport/__init__.py
bumble/transport/android_emulator.py
bumble/transport/android_netsim.py
bumble/transport/common.py
bumble/transport/pyusb.py
bumble/transport/usb.py

Replace builtin errors so they could be handled more properly. 
* Add BaseBumbleException as a "real" root error
* Add several core error classes and properly replace builtin errors with them
* Add several error classes for specific modules (transport, device)
Errors raised in Apps, Examples, Tests and Pandora are left because they are unlikely to be handled.

Reorganize exceptions

---

bumble/transport/__init__.py
bumble/transport/unix.py

Though sometimes UNIX sockets are mounted in filesystem, but they cannot be opened via file transport. Also there isn't a way to open abstract UNIX sockets.
The reason to use UNIX socket transport is because they have a less cost when the server is at the same host.

Add UNIX socket transport

---

bumble/transport/usb.py

A bit of cleanup of how USB transfers are managed:
1/ Instead of removing packets from the queue in the callback, they are now processed by a task
2/ a transfer semaphore is used to ensure that we don't start a new transfer while one is already in progress

USB: better packet queue logic

---

bumble/profiles/mcp.py
examples/leaudio.json
examples/mcp_server.html
examples/run_mcp_client.py
tests/mcp_test.py

We may also drop new Characteristic adapters, because MCS characteristics seldom get read.

Media Control Service Client implementation

---

bumble/device.py
bumble/hci.py
bumble/host.py
bumble/smp.py
examples/device_with_rpa.json
tests/device_test.py

This PR adds a device config to tell the Device object to automatically create a random private address at power on. Optionally, there's also a periodic task to update the RPA based on a configurable timeout.
For manual control, the `update_rpa` method can be called.

add basic RPA support

---

bumble/transport/common.py
bumble/transport/usb.py

The USB HCI source doesn't need a parser, since the USB transfers always contain a single HCI packet.
Not using a parser makes the implementation more robust against poorly behaved USB dongles that sometimes return transfer data with bogus/malformed data: with a parser, the parser may be stuck in a bad state. Without a parser we can just throw away malformed USB transfers and continue (the next transfers may contain valid data)

don't user a parser for a usb source

---

bumble/device.py
bumble/smp.py
tests/device_test.py
tests/smp_test.py

* Fix the bug which device doesn't generate a static address by default
* Properly distribute public or random address if no identity address type is set
* Add configurable identity address type and io capabilities

Fix CTKD failure introduced by Host RPA generation

---

bumble/device.py

Some controllers may report invalid RPA like when local is not using generation offloading or remote address is not RPA. Since RPA is always considered private, this will lead to some issues.

Ignore invalid RPA

---

bumble/transport/usb.py

the USB callback runs in the context of the USB loop thread, not the asyncio executor, so the call to release() must be deferred to an async context.

hotfix for usb transport

---

bumble/smp.py

Code change
- for DH Key compute , ra and rb values are based on shared OOB randomizer value
- oob_data_flag should be 1 if remote device oob data present
- initial shared OOB randomizer value should not modified
Please review the changes

 DH Key compute check modification for OOB Pairing

---

bumble/drivers/rtk.py
bumble/host.py

Replacement for #497 with the logic for the HCI parser removed now that packets are handled without a parser for USB. This bug was observed with some RTK BLE dongles (specifically cheaper CSR dongles as well as the Edimax BT-8500). Sometimes, when a reset is attempted, the host will fail to receive a result, instead receiving an invalid packet or corrupt data. This results in blocking forever in `driver_info_for_host()`. In testing, I found that allowing that to time out, then trying again can work with dongles like the Edimax.
With cheaper CSR dongles, sometimes the first packet in response to a command after the reset will be an invalid packet. This occurs when the Local Version request is sent. The result is similar to the above in which case we wait forever on a packet that isn't …

[Bug] Edimax BLE Dongle Fails After Teardown and Re-Instantiation

---

bumble/transport/android_netsim.py

If the `XDG_RUNTIME_DIR` environment variable does not exist, `netsim.ini` will instead be generated within the `/tmp` directory on linux.

Support netsim.ini tmpdir on linux

---

bumble/att.py

Removes a redundant whitespace character from the exception's message

Fix whitespace

---

docs/mkdocs/src/examples/index.md
examples/run_csis_servers.py

Amends the usage of the script and the example that show when executed incorrectly. 
Adds basic information to the `examples` section of the documentation.

run_csis_servers: Update `usage` and add docs entry

---

docs/mkdocs/src/examples/index.md
examples/run_cig_setup.py

- Changes the address type used during connecting to what is actually advertised by Device 0 by default (random address).
- Amends CIG Parameters to use values allowed by the Core specification.
- Updates the usage of the script and the example that show when executed incorrectly.
- Adds basic information to the `examples` section of the documentation.

examples/run_cig_setup: Fix the address type and CIG params

---

bumble/hfp.py
tests/hfp_test.py

The `data` received in `_read_at` may have multiple commands.
This fixes `execute_command` timing out when waiting for an `OK` response when it is in the same data buffer, e.g. during SLC initialization: b'\r\n+BRSF: 3904\r\n\r\nOK\r\n'

HFP: Fix reading multiple AT commands from a single data packet

---

.github/workflows/code-check.yml
.github/workflows/python-build-test.yml
bumble/avc.py
bumble/l2cap.py
bumble/link.py
bumble/profiles/bap.py
bumble/sdp.py
docs/mkdocs/src/getting_started.md
docs/mkdocs/src/index.md
docs/mkdocs/src/platforms/index.md
environment.yml
examples/run_extended_advertiser_2.py
examples/run_hfp_handsfree.py
pyproject.toml
setup.cfg

Python 3.8 is now end of life, and 3.13 has been released.

remove test for deprecated Python 3.8 and add 3.13

---

bumble/gatt_client.py

GATT Client's subscribe() adds the characteristic itself as subscriber. Therefore the characteristic has to be removed in unsubscribe(), if it's the last subscriber. Otherwise the clean up does not work correctly and the CCCD never is set back to 0 in the remote device.

Remove characteristic in GATT Client unsubscribe() if it's the last subscriber

---

tests/gatt_test.py

A GATT unsubscription bug was fixed recently. This adds a simple regression test for what was broken.

regression test for GATT unsubscription

---

apps/auracast.py
apps/lea_unicast/app.py
bumble/core.py
bumble/hci.py
bumble/profiles/bap.py
examples/run_unicast_server.py
tests/bap_test.py

* APP: Allow scanning for broadcast without name (check annoucement instead)
* Add BAP dataclass serializer
* Allow nullable codec specific configuration fields
* Remove BAP CodecID (use HCI CodecID/Format instead, though the term is a little bit confusing)

Improve Broadcast Scanning

---

bumble/device.py

Parses scan response data correctly just like advertising data does with hex string.

Correctly parse scan response from device config

---

bumble/profiles/aics.py

Corrects the Audio Input Control Point Opcode value for `Set Gain Setting` field.
As per the specifications `Audio Input Control Service v1.0`, section `3.5.1 Audio Input Control Point procedure requirements` the value should be 0x01.

Amend Opcode value in `Audio Input Control Service`

---

apps/hci_bridge.py
bumble/att.py
bumble/controller.py
bumble/core.py
bumble/device.py
bumble/gatt.py
bumble/gatt_client.py
bumble/gatt_server.py
bumble/hci.py
bumble/host.py
bumble/l2cap.py
bumble/profiles/bap.py
bumble/sdp.py
bumble/smp.py
tests/gatt_test.py
tests/hci_test.py
tests/self_test.py

The use of `to_bytes` should be reserved for cases where an argument is needed (like `int.to_bytes()`). For all other cases, `__bytes__` should be used.
For legacy reasons, the code base still had a few places where `to_bytes` was called (and classes where both `__bytes__` and `to_bytes` were defined).
This PR cleans up these cases.

only use `__bytes__` when not argument is needed.

---

.github/workflows/code-check.yml
.github/workflows/python-avatar.yml
setup.cfg

This way, type checking works for any user with the `development` dependencies.

move pandora deps to development

---

pyproject.toml

To allow users to have versions of the cryptography dependency that are >= 39

update cryptography dependency

---

apps/auracast.py
apps/lea_unicast/app.py
bumble/device.py
bumble/profiles/ascs.py

* Make a base `_IsoLink` class to allow sharing methods between CIS and BIS
* Fix some minor bugs and type annotations

Unify ISO methods

---

bumble/hci.py
bumble/vendor/android/hci.py
tests/hci_test.py

While there's no way to ensure the uniqueness of HCI vendor event codes across vendors, it is still possible to have vendor event factories that don't overlap (by design), such as the generic set of Android vendor HCI events which multiple vendors do implement (and in that case the vendors ensure that they don't re-use the same event codes for other events).
This change allows having multiple vendor factories, which will be invoked in registration order when an HCI vendor event is encountered, instead of a single factory. It is up to the caller to ensure that they do not register factories with overlapping IDs.

support multiple event factories

---

bumble/device.py

`_IsoLink.write()` raises  `struct.error: 'H' format requires 0 <= number <= 65535` exception. Further discussed [here](https://github.com/google/bumble/issues/621#issue-2779021902).

Fix: _IsoLink.write() struct.exception

---

bumble/device.py

Fix `scan_interval ` for the `hci.HCI_LE_Set_Extended_Scan_Parameters_Command` used for setting scan params (see https://github.com/google/bumble/issues/625)

Update device.py - Fix scan_interval param in hci.HCI_LE_Set_Extended_Scan_Parameters_Command

---

apps/auracast.py
apps/controller_info.py
bumble/controller.py
bumble/device.py
bumble/hci.py
bumble/host.py
tests/device_test.py
tests/hci_test.py
tests/host_test.py

ISO packets for BIS and CIS are now sent to the controller via an HCI packet queue that respects the buffering requirements of the controller.
In addition, the packet queues are made visible to the API users (advanced use case), and can emit 'drain' events when packets are marked as completed by the controller (this can be used for sending data at the right rate, rather than rely on a timer).
NOTE: the change to use the `drain` event rather than a timer in the `auracast` app is not included in this PR (coming in a later PR), but the use of the `drain` even is add, just to print the buffer levels as the packets are being sent (and we can see that with a timer approach, packets end up being buffered, which may become a problem eventually for long running streams, but this will get fixed in …

add support for ACL and ISO HCI packet queues

---

bumble/device.py

To allow full range of scanning and connection parameter types (e.g. connection_interval = [7.5 ms to 4 s]), some parmeter types were changed from `int `to `float`

Adapt scanning and connection parameters type

---

bumble/sdp.py

Since https://github.com/google/bumble/pull/629, `search_attributes()` takes a tuple of (begin, end) instead of (value, size), so this value should be altered as well.

Correct SDP_ALL_ATTRIBUTES_RANGE value

---

rust/README.md
rust/examples/broadcast.rs
rust/pytests/wrapper/hci.rs
rust/src/wrapper/hci.rs

* Fix error code extraction from Python to Rust
* Add documentation for dealing with HCI packets

Rust library cleanup

---

apps/auracast.py
apps/device_info.py
bumble/audio/__init__.py
bumble/audio/io.py
bumble/device.py
bumble/gatt.py
bumble/gatt_client.py
bumble/profiles/aics.py
bumble/profiles/asha.py
bumble/profiles/bass.py
bumble/profiles/gmap.py
bumble/profiles/le_audio.py
bumble/profiles/pacs.py
bumble/profiles/tmap.py
bumble/profiles/vcs.py
bumble/profiles/vocs.py
docs/mkdocs/mkdocs.yml
docs/mkdocs/src/apps_and_tools/index.md
docs/mkdocs/src/getting_started.md
docs/mkdocs/src/platforms/android.md
examples/run_gatt_with_adapters.py
examples/run_vcp_renderer.py
pyproject.toml
tests/aics_test.py
tests/import_test.py
tests/vcp_test.py
tests/vocs_test.py

This allows the auracast app to use the host's sound devices for input and output, in addition to other input and output types (file, stdio, external process).
The dependency on lc3 has changed, because PyPI does not allow `git` external dependencies.
Also included are small changes to some of the LE Audio GATT services, to use object types instead of raw bytes or tuples where appropriate (there are still maybe a few characteristics left to 'objectify', which can be done in subsequent PRs).
A later PR will include improvements to the typing support for GATT adapters.

auracast audio io

---

apps/auracast.py

The auracast app only starts work again if we call setup_data_path after instantiating the IsoPacketStream object.
Before this change, the Number of completed packages event from controller to host always returns a zero handle like so:
```
< ISO Data TX: Handle 39 flags 0x02 dlen 104                                                                                                                                      #97 284.682500
> HCI Event: Number of Completed Packets (0x13) plen 5                                                                                                                            #98 284.682700
Num handles: 1
Handle: 0
Count: 1
```
After this change, The broadcast is sent without any errors and can also be received with a pair of earbuds.
The setup that was used …

Add setup_data_path for iso queues

---

apps/auracast.py
bumble/core.py
bumble/device.py
bumble/pairing.py

* Add overloads to provide better return type hints
* Make advertising data type enum so they can be considered constants

Improve AdvertisingData type annotations

---

bumble/host.py

Host raises `AttributeError` exception (NoneType hs no attribute flush) for `self.acl_packet_queue.flush()` when the Controller does not support the `hci.HCI_BUFFER_SIZE_COMMAND `(e.g. the Laird 654 Connectivity Dongle for the official Bluetooth SIG Qualification PTS tests).

FIX - acl_packet_queue.flush 

---

apps/auracast.py

Now that IsoLink has a `set_data_path method`, use it in `auracast.py` instead of sending an HCI command directly.

use bis link API

---

bumble/device.py

Typo was causing LE scanning duty cycle to be locked at 100% due to the le_scan_window and le_scan_interval both being set to scan window.

Fixed le_scan_interval incorrectly being set with scan_window

---

bumble/controller.py
bumble/core.py
bumble/device.py
bumble/hci.py
bumble/host.py
bumble/l2cap.py
bumble/link.py
bumble/pandora/host.py
bumble/pandora/security.py
bumble/pandora/utils.py
bumble/smp.py
bumble/transport/usb.py
tests/device_test.py
tests/self_test.py

As they are widely used as parameters, making them enums can significantly improve the static check.

Enumify: PhysicalTransport, Role, AddressType

---

apps/auracast.py
bumble/profiles/pbp.py
bumble/transport/common.py

Support for proper encoding of broadcast code from strings to 16-byte values.
Also includes a fix for parsing `PublicBroadcastAnnouncement` correctly and printing more info about BIGs.

add broadcast code encoding

---

bumble/l2cap.py

According to the Bluetooth Core Spec, Volume 3, Part A, Section 4, 0x00 is an invalid identifier:
4. Signaling packet formats ...
Identifier (1 octet)
... Signaling identifier 0x00 is an invalid identifier and shall never be used in any command.

Fix L2CAP signaling packet identifiers

---

bumble/att.py
bumble/avctp.py
bumble/avdtp.py
bumble/avrcp.py
bumble/device.py
bumble/gatt.py
bumble/gatt_client.py
bumble/gatt_server.py
bumble/hfp.py
bumble/hid.py
bumble/l2cap.py
bumble/pandora/host.py
bumble/pandora/l2cap.py
bumble/pandora/security.py
bumble/profiles/ancs.py
bumble/profiles/ascs.py
bumble/profiles/asha.py
bumble/profiles/hap.py
bumble/profiles/mcp.py
bumble/profiles/vcs.py
bumble/rfcomm.py
bumble/smp.py

Emitting and listening to literal events are dangerous because:
1. When event name changes, type checker cannot capture the error
2. Some long event names could be typo
So we should make them constants.
This PR also typified and corrected some AVDTP functions.
For host, since current composite listeners relies on the event name, we may change it in another PR.

Declare emitted events as constants

---

apps/bench.py
apps/console.py
bumble/device.py
bumble/hci.py
bumble/host.py
pyproject.toml

There were still a few places where the timescales were not properly converted between the internal (HCI) level and the external (Device API) level.
The basic rule is that at the "user" level, the Device API should always try to hide some of the low-level details, including some the HCI-level timescales (where some time values are expressed, for example, in units of 1.25ms or 0.625ms).
This means that data structure and parameters at the `host.py` level (including parameters for events emitted by the `Host` object) use the low level HCI timescales, whereas public data structures and parameters at the `device.py` level use higher level "natural" units (seconds, milliseconds, ...).
This change also includes support for `HCI_LE_Enhanced_Connection_Complete_V2_Event` which was missing.

fix a few timescale adjustments

---

bumble/device.py
bumble/keys.py
bumble/pandora/security.py
bumble/smp.py

Link key type is not bound to connection but peer address, so it makes more sense to store them in keystore instead of connection object.

Move connection.link_key_type to keystore

---

pyproject.toml

cryptography: bump version to 44.0.3 to fix python parsing

---

bumble/drivers/intel.py

Tested with AX211 on an MSI board, using ibt-1040-0041.sfi from linux-firmware.
Firmware loads (after reboot to bootloader), then the controller functions well (ISO fails, but that might be another topic).
Signed-off-by: Dmitrii Sharshakov <d3dx12.xx@gmail.com>

intel: add Garfield Peak GfP2 and AX211 firmware loading

---

bumble/device.py
bumble/profiles/ascs.py

Unlike `HCI_LE_Setup_ISO_Data_Path_Command`, `HCI_LE_Remove_ISO_Data_Path_Command` takes a flag parameter instead of an enum parameter.

Fix wrong remove iso data path parameter

---

apps/bench.py
bumble/device.py

This allows experimenting with the behavior of the controller when sending/receiving data while a scan and/or advertising is still going on.

add advertise and scan options to the bench app

---

apps/speaker/speaker.html
apps/speaker/speaker.js
apps/speaker/speaker.py
bumble/a2dp.py

Adding support for Opus playback. Should work in Chrome (not tested on other browsers).
This shifts from using MSE, which isn't very good for low latency, to using WebAudio and WebCodecs, which gives us a much better latency, and supports both AAC and Opus streams.
This PR also includes a few command line options to allow controlling which bitrates and sampling frequencies are advertised. 
Also added to the UI: display the current bitrate (averaged over the last ~30 buffers).

speaker app: enable opus, enable more options

---

bumble/hci.py
bumble/profiles/ascs.py
tests/bap_test.py

This has been used in [Navi](https://github.com/google/bt-navi-tests/blob/main/navi/bumble_ext/hci.py) for a while. Recently I resolved several critical issues and I think it's a time to bring it into Bumble upstream.
An obvious benefit to use dataclasses is IDE and type checker integration. 
Unlike https://github.com/google/bumble/pull/430, this design properly utilize the existing effort, especially field specs. For nested fields, we may need to set another field in metadata like `Annotated[list, 1, '[' or ']' ]` as stack operator, though usually we only support up to 2 layers.
return_parameters_fields cannot be benifit from this, because current type checker cannot associate two classes. But BTW, return_parameters_fields is actually not necessary to be inside decorator, so later we may …

Dataclass-based ASCS Packets

---

bumble/controller.py
bumble/hci.py
bumble/host.py
tests/device_test.py
tests/hci_test.py

op_code is usually set to class (not instance) inside decorators, and passing it to __init__ is not a common scenario, so here we change the order of __init__ to force it a keyword argument.
Also replace some legacy `registered` commands with listed fields.

HCI: Avoid patching __init__

---

bumble/hci.py
tests/hci_test.py

The original solution to register a packet class is little bit complicated, like:
1. (If opcode or event code is not registered yet) define a HCI* constants and call register function
2. Define packet classes with a hybrid case of name, which is usually considered incompliant by linters
The new approach allows classes declares these parameters as members.

Allow register HCI packets with custom names

---

bumble/avrcp.py
bumble/pandora/__init__.py
pyproject.toml
tests/hfp_test.py

Recent versions of vscode require black >= 25.1 for the python formatter.

update to black 25.1

---

bumble/controller.py
bumble/device.py
bumble/hci.py
bumble/host.py
tests/device_test.py

Handle the following HCI commands / events and make device API for them
1. HCI_LE_Subrate_Change
2. HCI_LE_Set_Default_Subrate
3. HCI_LE_Subrate_Request

Support LE Subrating

---

bumble/audio/io.py
bumble/avctp.py
bumble/avdtp.py
bumble/avrcp.py
bumble/device.py
bumble/gatt_server.py
bumble/host.py
bumble/l2cap.py
bumble/rfcomm.py
bumble/sdp.py
bumble/smp.py
bumble/transport/__init__.py
bumble/transport/common.py
bumble/transport/pyusb.py
bumble/transport/usb.py
bumble/utils.py

Many exceptions cannot be properly formatted as string, and miss stacktrace.

Always log exception using logging.exception

---

bumble/transport/__init__.py
bumble/transport/android_emulator.py
bumble/transport/android_netsim.py
bumble/transport/tcp_client.py
bumble/transport/tcp_server.py
bumble/transport/udp.py
bumble/transport/unix.py
bumble/transport/ws_server.py
tests/transport_tcp_server_test.py
tests/transport_test.py

* Support IPv6 schema
* Add transport integration tests
* Add UNIX socket server

Enhance transports

---

.vscode/settings.json
apps/auracast.py
apps/lea_unicast/app.py
apps/pair.py
apps/scan.py
bumble/core.py
bumble/data_types.py
bumble/device.py
bumble/hci.py
bumble/profiles/asha.py
bumble/profiles/bap.py
bumble/utils.py
examples/battery_server.py
examples/device_information_server.py
examples/heart_rate_server.py
examples/keyboard.py
examples/run_advertiser.py
examples/run_asha_sink.py
examples/run_csis_servers.py
examples/run_hap_server.py
examples/run_mcp_client.py
examples/run_unicast_server.py
examples/run_vcp_renderer.py
tests/core_test.py
web/heart_rate_monitor/heart_rate_monitor.py

This adds a class-based approach to advertising data (and other "data types"). The old ad-hoc model is still supported, but this is a cleaner approach with better type safety.
The main class `DataType` is defined in `core.py` but the subclasses are defined in `data_types.py`, to avoid circular dependencies.

add support for data type classes

---

bumble/avrcp.py
bumble/hci.py
tests/avrcp_test.py

* Change for strings in AVRCP: We now always try to parse strings as UTF-8 and fallback to laten-1 to simplify the implementation, because AVRCP spec only specifies this charset and the popularity of UTF-8 is a fait accompli.
* Add byteorder argument to hci spec.

AVRCP: Implement most commands and responses

---

.github/workflows/python-build-test.yml
rust/Cargo.toml

package `rayon-core v1.13.0` cannot be built because it requires rustc 1.80 or newer, while the currently active rustc version is 1.76.0.

Upgrade Rust to 1.80.0

---

bumble/host.py
bumble/transport/android_netsim.py
bumble/transport/serial.py
docs/mkdocs/src/transports/serial.md

This adds an option to introduce a short delay after opening a serial port (can be useful for HW that has a setup time, like the Nordic HW flow control auto-detect).

enhance serial port transport
